repos:
  - repo: https://github.com/dominikh/go-tools
    rev: master
    hooks:
      - id: staticcheck

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.56.2
    hooks:
      - id: golangci-lint
