name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install dependencies
        run: go mod tidy

      - name: Run Lint and Security
        run: |
          go fmt ./...
          go vet ./...
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          gosec ./...

      - name: Run Tests
        run: go test ./...
